### ISSUE TITLE
Movie recommendations

### ISSUE THREAD

**Issue by leereilly** [lee-dohm/ama#1]
Word on the street is that you know a thing or two about movies. Any recommendations for a _huge_ fan of movies like [Deep Rising :octopus: ](http://www.imdb.com/title/tt0118956/) , [Lake Placid :crocodile:](http://www.imdb.com/title/tt0139414/), [Army of Darkness :skull:](http://www.imdb.com/title/tt0106308/), and [Cabin in the Woods :evergreen_tree::house::deciduous_tree:](http://www.imdb.com/title/tt1259521/)?

Asking for a friend.

**Comment by lee-dohm** [comment]
It sounds like you ... I mean your friend ... is a fan of the rarefied "comedy horror" genre! Of course, it depends on whether you're in the mood for more comedy ... or more horror. But don't worry, I've got suggestions ... for your friend, naturally :grinning:
- If you're in the mood for more comedy than horror (or you're just a [Bruce Cambpell](http://www.imdb.com/name/nm0132257/) fan), I'd recommend [Bubba Ho-Tep](http://www.imdb.com/title/tt0281686/). Elvis and JFK fight off a mummy in a nursing home!
- If you're in the mood for a decent balance, I'd recommend [Zombieland](http://www.imdb.com/title/tt1156398/). It's like the Odd Couple meet Zombies!
- If you're in the mood for more comedy than horror, the classic is of course [Shaun of the Dead](http://www.imdb.com/title/tt0365748/).
- And finally, if you're just looking for a horror movie that is a little deeper than your typical horror/slasher/torture-porn/blood-and-guts marathon, I would recommend [Triangle](http://www.imdb.com/title/tt1187064/). It starts a little slow, but I feel it is rewarding if you stick with it.

I hope Mr. or Ms. Glass gets a lot of enjoyment from these movies!

**Comment by leereilly** [comment]
My friend (Leigh) is a fan of all of those movies, but had never heard of [Triangle  :small_red_triangle: ](http://www.imdb.com/title/tt1187064/). Once the kids go to bed, they'll be watching it for sure :+1:

Cheers,
  Lee :beers:
